[package]
name = "e64br"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
args = "2.2.0"
bitflags = "2.3.3"
getopts = "0.2.21"
itertools = "0.11.0"
lazy_static = "1.4.0"
packed_struct = "0.10.1"
